project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN
base_path: "./lib/l10n"
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  - source: "/intl_en.arb"
    translation: "%original_path%/intl_%two_letters_code%.arb"