# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Prod .ipa

on:
  workflow_dispatch:

env:
  FLAVOR: "prod"

jobs:
  build:
    name: Build .ipa
    runs-on: macos-11
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Connect private iap package
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.M3_LIGHTMETER_IAP_KEY }}

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APP_STORE_P12 }}
          p12-password: ${{ secrets.APP_STORE_P12_PASSWORD }}
      - name: Install the provisioning profile
        run: |
          PROVISION_CERT_PATH=$RUNNER_TEMP/Lightmeter.mobileprovision
          bash .github/scripts/restore_from_base64.sh "${{ secrets.APP_STORE_PROVISION_PROD }}" $PROVISION_CERT_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PROVISION_CERT_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Restore firebase_options.dart
        run: bash .github/scripts/restore_from_base64.sh "${{ secrets.FIREBASE_OPTIONS }}" "lib/firebase_options.dart"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.0"

      - name: Prepare flutter project
        run: |
          flutter --version
          flutter pub get
          flutter pub run intl_utils:generate

      - name: Build .ipa
        run: flutter build ipa --release --flavor $FLAVOR -t lib/main_$FLAVOR.dart

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: m3_lightmeter_$FLAVOR_ipa
          path: build/ios/ipa/lightmeter.ipa
