# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pull Request check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-11
    timeout-minutes: 5

    steps:
      - uses: shaunco/ssh-agent@git-repo-mapping
        with:
          ssh-private-key: |
            ${{ secrets.M3_LIGHTMETER_IAP_KEY }}
          repo-mappings: |
            github.com/vodemn/m3_lightmeter_iap

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate intl
        run: flutter pub run intl_utils:generate

      - name: Analyze project source
        run: flutter analyze lib --fatal-infos
#      - name: Run tests
#        run: flutter test
