name: Crowdin pull
on:
  workflow_dispatch:
  repository_dispatch:
    types: [crowdin-webhook]
concurrency:
  group: ${{ github.workflow }}
permissions:
  contents: write
  pull-requests: write
env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  CROWDIN_PROJECT_ID: 567473
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
jobs:
  download-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Download
        uses: crowdin/github-action@1.5.0
        with:
          crowdin_branch_name: main
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_strings: true
          export_only_approved: true
          push_translations: true
          localization_branch_name: main-l10n
          create_pull_request: true
          pull_request_base_branch_name: main
